version: "3"

services:
  api:
    user: smaf
    build:
      context: smaf-api/api
      dockerfile: docker/Dockerfile
    command: npm run start
    networks:
      my-network:
        aliases:
          - smaf-api
    ports:
      - "8000:3000"
    volumes:
      - ./smaf-api/api:/home/smaf/smafApi/api/app
    restart: always
networks:
  my-network:
